#-----------------
# CLUSTER DISCOVERY by env
#-----------------
# db-pg-akira-encrypted.cr92yss80klo.eu-west-1.rds.amazonaws.com:5432:*:foo
[CLS1]
dev=ca06srv.cdbdx.xxx
rec=ca04srv.cdweb.xxx
ppA=ca01srv.cdweb.xxx
ppB=ca02ssrv.cdweb.xxx
prA=ca02srv.cdweb.xxx
prB=ca01ssrv.cdweb.xxx
[CLS2]
dev=ca06srv.cdbdx.xxx
rec=ca04srv.cdweb.xxx
ppA=ca02srv.cdweb.xxx
ppB=ca02ssrv.cdweb.xxx
prA=ca01srv.cdweb.xxx
prB=ca01ssrv.cdweb.xxx
[CLS3]
dev=ca06srv.cdbdx.xxx
rec=ca04srv.cdweb.xxx
ppA=ca02srv.cdweb.xxx
ppB=ca02ssrv.cdweb.xxx
prA=ca01srv.cdweb.xxx
prB=ca01ssrv.cdweb.xxx
[CLS4]
dev=ca06srv.cdbdx.xxx
rec=ca04srv.cdweb.xxx
ppA=ca02srv.cdweb.xxx
ppB=ca02ssrv.cdweb.xxx
prA=ca01srv.cdweb.xxx
prB=ca01ssrv.cdweb.xxx
[CLS5]
dev=ca06srv.cdbdx.xxx
rec=ca04srv.cdweb.xxx
ppA=ca02srv.cdweb.xxx
ppB=ca02ssrv.cdweb.xxx
prA=ca01srv.cdweb.xxx
prB=ca01ssrv.cdweb.xxx
[CLS6]
dev=ca06srv.cdbdx.xxx
rec=ca04srv.cdweb.xxx
ppA=ca02srv.cdweb.xxx
ppB=ca02ssrv.cdweb.xxx
prA=ca01srv.cdweb.xxx
prB=ca01ssrv.cdweb.xxx
